p= int(input("ingrese la presion a calcular:"))
v= int(input("ingrese el volumen a calcular:"))
t= int(input("ingrese la tempraturaa calcular:"))
masa= (p*v)/((0.37*t+460))
print("la masa seria de:",masa)